In [119]:
# where was this in comp sci?> could have done all my math work as programming assignments!

In [118]:
import numpy as np # import additional functions, installed via "conda install numpy" | could "from numpy.random import randint"

In [3]:
my_list = [1, 2, 3] # casting from python to numpy arrays

In [4]:
arr1d = np.array(my_list)

In [17]:
arr1d # single set of brackets for a 1d array

array([1, 2, 3])

In [6]:
my_matrix = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [7]:
arr2d = np.array(my_matrix)

In [18]:
arr2d # 2 sets for brackets for a 2d array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
np.arange(0,10) # similar to range, can do third argument for stepsize (only evens for example)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
np.zeros(3)

array([ 0.,  0.,  0.])

In [15]:
np.zeros((2, 3)) # create based on dimensions given

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [16]:
np.ones((5,5))

array([[ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.]])

In [140]:
np.linspace(0, 5, 25) # still a 1d array, watch the jupyter formatting - notice single ]

array([ 0.        ,  0.20833333,  0.41666667,  0.625     ,  0.83333333,
        1.04166667,  1.25      ,  1.45833333,  1.66666667,  1.875     ,
        2.08333333,  2.29166667,  2.5       ,  2.70833333,  2.91666667,
        3.125     ,  3.33333333,  3.54166667,  3.75      ,  3.95833333,
        4.16666667,  4.375     ,  4.58333333,  4.79166667,  5.        ])

In [23]:
np.eye(4) # identity matrix | must be square

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]])

In [24]:
np.random.rand(5) # tons of different randomization submethods, this is between 0-1

array([ 0.61846322,  0.77648633,  0.68777752,  0.39810869,  0.00202261])

In [25]:
np.random.rand(5, 5)

array([[ 0.67392537,  0.08455623,  0.2905418 ,  0.3020072 ,  0.44452605],
       [ 0.07644781,  0.79535717,  0.40303974,  0.99530307,  0.04393982],
       [ 0.68987894,  0.21280297,  0.83280032,  0.02703727,  0.26459418],
       [ 0.46578902,  0.84206049,  0.20053446,  0.890739  ,  0.69730657],
       [ 0.27172796,  0.899532  ,  0.08356036,  0.71632211,  0.27481773]])

In [30]:
np.random.randn(10) # random centered aroudn 0, also works with 2d

array([ 0.46571551, -1.4508735 , -0.07804522, -0.31200024, -1.05387635,
       -1.33341961,  1.31116509, -0.35343747, -1.71957705, -0.98134238])

In [33]:
np.random.randint(1, 100, 8) # inclusive low end, exclusive heigh end (100 will never be picked), how many you want?

array([70, 55, 65, 44, 64, 19, 53, 12])

In [34]:
arr = np.arange(25)

In [35]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [36]:
ranarr = np.random.randint(0, 50, 10)

In [46]:
arr = arr.reshape(5, 5) # convert the previously created array of 25 into a 5x5 - watch overflow

In [39]:
ranarr.max()

48

In [40]:
ranarr.min()

5

In [41]:
ranarr.argmax()

1

In [42]:
ranarr

array([19, 48, 15, 26, 37, 20, 27, 20, 28,  5])

In [43]:
ranarr.argmin()

9

In [47]:
arr.shape # dumping back without the ()

(5, 5)

In [52]:
arr.dtype

dtype('int64')

In [53]:
# indexing

In [56]:
arr = np.arange(0, 10)

In [57]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [58]:
arr[8]

8

In [61]:
arr[0:5] # start:stop can do 5: or :5 same as lists

array([0, 1, 2, 3, 4])

In [62]:
arr[0:5] = 100 # numpy arrays can do "broadcasting"

In [63]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9])

In [64]:
arr = np.arange(0, 10)

In [71]:
slice_of_array = arr[0:6] # original slice - this wont copy because you dont want to duplicate data on huge arrays

In [66]:
slice_of_array

array([0, 1, 2, 3, 4, 5])

In [75]:
slice_of_array[:] = 99 # broadcast all

In [68]:
slice_of_array

array([99, 99, 99, 99, 99, 99])

In [69]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9])

In [74]:
arr_copy = arr.copy() # if you actually want to copy the original array instead of linking to it as above

In [73]:
arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9])

In [102]:
arr_2d = np.array([[5, 10, 15], [20, 25, 30], [35, 40, 45]]) # some 2d action

In [77]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [82]:
arr_2d[1][2] # double bracket notation

30

In [84]:
arr_2d[0] # snag single row

array([ 5, 10, 15])

In [85]:
arr_2d[1, 2] # same as above, different notation

30

In [87]:
arr_2d[:2,1:] # using slice notation

array([[10, 15],
       [25, 30]])

In [91]:
arr_2d[2:,0:]

array([[35, 40, 45]])

In [93]:
arr_2d[:0,0:] # not what i expected

array([], shape=(0, 3), dtype=int64)

In [99]:
arr_2d[:,2:] # want row 0, 1, 2 and only column 2 onward

array([[15],
       [30],
       [45]])

In [101]:
arr_2d[:,2] # without the slice - prints as horizontal

array([15, 30, 45])

In [103]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9])

In [104]:
arr = np.arange(1, 11)

In [105]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [113]:
arr > 5 # cool!

array([False, False, False, False, False,  True,  True,  True,  True,  True], dtype=bool)

In [107]:
bool_arr = arr > 5

In [110]:
arr[bool_arr] # conditional indexing

array([ 6,  7,  8,  9, 10])

In [112]:
arr[arr>5] # can be combined into a single statement

array([ 6,  7,  8,  9, 10])

In [114]:
arr_2d2 = np.arange(50).reshape(5, 10)

In [115]:
arr_2d2

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [117]:
arr_2d2[1:3, 3:5] # look at rows 1 and 2, then columns 3 and 4

array([[13, 14],
       [23, 24]])

In [122]:
arr = np.arange(0, 11)

In [123]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [124]:
arr * arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [125]:
arr + 100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [127]:
arr / arr # nan (no object back) - continues to run on a division by 0

/home/tyler/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([ nan,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.])

In [128]:
1 / arr # infinity 

/home/tyler/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([        inf,  1.        ,  0.5       ,  0.33333333,  0.25      ,
        0.2       ,  0.16666667,  0.14285714,  0.125     ,  0.11111111,
        0.1       ])

In [130]:
arr ** 2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [139]:
np.sqrt(arr) # universal functions docs.scipy.org/doc/numpy/reference/ufuncs.html basic/trig/geo/etc...

array([ 0.        ,  1.        ,  1.41421356,  1.73205081,  2.        ,
        2.23606798,  2.44948974,  2.64575131,  2.82842712,  3.        ,
        3.16227766])

In [134]:
np.exp(arr)

array([  1.00000000e+00,   2.71828183e+00,   7.38905610e+00,
         2.00855369e+01,   5.45981500e+01,   1.48413159e+02,
         4.03428793e+02,   1.09663316e+03,   2.98095799e+03,
         8.10308393e+03,   2.20264658e+04])

In [135]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [138]:
np.log(arr) # negative infinity!

/home/tyler/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([       -inf,  0.        ,  0.69314718,  1.09861229,  1.38629436,
        1.60943791,  1.79175947,  1.94591015,  2.07944154,  2.19722458,
        2.30258509])