In [49]:
import numpy as np # import additional functions, installed via "conda install numpy" | could "from numpy.random import randint"

In [3]:
my_list = [1, 2, 3] # casting from python to numpy arrays

In [4]:
arr1d = np.array(my_list)

In [17]:
arr1d # single set of brackets for a 1d array

array([1, 2, 3])

In [6]:
my_matrix = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [7]:
arr2d = np.array(my_matrix)

In [18]:
arr2d # 2 sets for brackets for a 2d array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
np.arange(0,10) # similar to range, can do third argument for stepsize (only evens for example)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
np.zeros(3)

array([ 0.,  0.,  0.])

In [15]:
np.zeros((2, 3)) # create based on dimensions given

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [16]:
np.ones((5,5))

array([[ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.]])

In [29]:
np.linspace(0, 5, 25) # still a 1d array, watch the jupyter formatting 

array([ 0.        ,  0.20833333,  0.41666667,  0.625     ,  0.83333333,
        1.04166667,  1.25      ,  1.45833333,  1.66666667,  1.875     ,
        2.08333333,  2.29166667,  2.5       ,  2.70833333,  2.91666667,
        3.125     ,  3.33333333,  3.54166667,  3.75      ,  3.95833333,
        4.16666667,  4.375     ,  4.58333333,  4.79166667,  5.        ])

In [23]:
np.eye(4) # identity matrix | must be square

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]])

In [24]:
np.random.rand(5) # tons of different randomization submethods, this is between 0-1

array([ 0.61846322,  0.77648633,  0.68777752,  0.39810869,  0.00202261])

In [25]:
np.random.rand(5, 5)

array([[ 0.67392537,  0.08455623,  0.2905418 ,  0.3020072 ,  0.44452605],
       [ 0.07644781,  0.79535717,  0.40303974,  0.99530307,  0.04393982],
       [ 0.68987894,  0.21280297,  0.83280032,  0.02703727,  0.26459418],
       [ 0.46578902,  0.84206049,  0.20053446,  0.890739  ,  0.69730657],
       [ 0.27172796,  0.899532  ,  0.08356036,  0.71632211,  0.27481773]])

In [30]:
np.random.randn(10) # random centered aroudn 0, also works with 2d

array([ 0.46571551, -1.4508735 , -0.07804522, -0.31200024, -1.05387635,
       -1.33341961,  1.31116509, -0.35343747, -1.71957705, -0.98134238])

In [33]:
np.random.randint(1, 100, 8) # inclusive low end, exclusive heigh end (100 will never be picked), how many you want?

array([70, 55, 65, 44, 64, 19, 53, 12])

In [34]:
arr = np.arange(25)

In [35]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [36]:
ranarr = np.random.randint(0, 50, 10)

In [46]:
arr = arr.reshape(5, 5) # convert the previously created array of 25 into a 5x5 - watch overflow

In [39]:
ranarr.max()

48

In [40]:
ranarr.min()

5

In [41]:
ranarr.argmax()

1

In [42]:
ranarr

array([19, 48, 15, 26, 37, 20, 27, 20, 28,  5])

In [43]:
ranarr.argmin()

9

In [47]:
arr.shape # dumping back without the ()

(5, 5)

In [48]:
arr.dtype

dtype('int64')